#!/usr/bin/env python3
"""Render data/midi_param_tables.json as markdown reference pages (docs/params/*.md).

One page per section (Performance Common, Performance Part, AWM2 Element, Drum Key, FM-X, AN-X,
System, Live Set, Curve). Each table lists offset, size, key (the name used by tools/pfm.py),
printed range/description, default and notes. The `.pfm` block a table maps to is given where known.
"""
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import pfm  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "docs", "params")
PAGES = {
    "PERFORMANCE COMMON": "performance-common.md",
    "PERFORMANCE PART": "performance-part.md",
    "NORMAL PART ELEMENT": "awm2-element.md",
    "DRUM VOICE KEY": "drum-key.md",
    "FM-X PART COMMON": "fmx-part.md",
    "AN-X PART": "anx-part.md",
    "SYSTEM": "system.md",
    "LIVE SET": "live-set.md",
    "CURVE": "curve.md",
    "BULK CONTROL": "bulk-control.md",
}


def main():
    raw = json.load(open(os.path.join(HERE, "..", "data", "midi_param_tables.json")))
    block_of = {v: k for k, v in pfm.TABLE_OF.items()}
    pages = {}
    for t in raw["tables"]:
        pages.setdefault(t["section"], []).append(t)
    os.makedirs(OUT, exist_ok=True)
    index = ["# Parameter reference (generated from the MONTAGE M Data List, MW-H0)\n",
             "Generated by `tools/gen_param_docs.py` from `data/midi_param_tables.json`. Keys are the names",
             "`tools/pfm.py` uses in `decode_performance` / `encode_block`; values are the raw Data List values",
             "(2-byte values are MSB*128+LSB; bipolar ranges are offset, e.g. `−64 – +63` with default `00 40`",
             "means raw − 64). Effect types: see `data/effect_types.json`.\n"]
    for section, tables in pages.items():
        fn = PAGES.get(section, re.sub(r"[^a-z0-9]+", "-", section.lower()) + ".md")
        lines = [f"# {section}\n"]
        for t in tables:
            blk = block_of.get(t["base"])
            size_note = "" if t["size_ok"] else f" (Data List prints TOTAL SIZE {t['total_size']}; rows and files give {t['calc_size']})"
            lines.append(f"## `{t['base']}` — {t['calc_size']} bytes{size_note}")
            if blk:
                lines.append(f"`.pfm` block: `{blk}`")
            if t["footnotes"]:
                lines.append("_" + " ".join(t["footnotes"]) + "_")
            lines.append("")
            lines.append("| off | sz | key | range / values | default | notes |")
            lines.append("|---|---|---|---|---|---|")
            seen = {}
            for p in t["params"]:
                key = p["name"] or f"param_{p['offset']}"
                if key in seen:
                    key = f"{key} @{p['offset']}"
                seen[key] = True
                desc = p["desc"].replace("|", "\\|")
                rng = p["range"].replace("|", "\\|")
                cell = desc if desc else rng
                if desc and rng and not re.search(r"[0-9A-F]{2} [0-9A-F]{2}|^[0-9A-F]{2}", rng) is None and not desc:
                    cell = rng
                lines.append(f"| {p['offset']} | {p['size']} | {key} | {cell} | {p['default']} | {p['notes'].replace('|', '/')[:80]} |")
            lines.append("")
        open(os.path.join(OUT, fn), "w").write("\n".join(lines))
        index.append(f"- [{section}]({fn}) — {len(tables)} tables, {sum(len(t['params']) for t in tables)} parameters")
    open(os.path.join(OUT, "README.md"), "w").write("\n".join(index) + "\n")
    print("wrote", len(pages), "pages to", OUT)


if __name__ == "__main__":
    main()
